version: "3.9"

services:
  # Pythonコンテナ
  python:
    stdin_open: true
    tty: true
    restart: always
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --notebook-dir=/workspace
    expose:
      - "8888"
    # 下記の左の番号だけを変更する
    ports:
      - "7243:8888"
    volumes:
      - ../workspace:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    container_name: python
    build:
      context: ./python
      dockerfile: Dockerfile

  # rapidsコンテナ
  rapids:
    stdin_open: true
    tty: true
    volumes:
      - ../workspace:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    container_name: rapids
    build:
      context: ./rapids
      dockerfile: Dockerfile
    
  # neologdnコンテナ
  neologd:
    container_name: "neologd"
    # image: "mecab-python-neologd"
    build:
      context: ./neologd
      dockerfile: Dockerfile
    volumes:
      - "../workspace:/workspace"
    tty: true

    #GPUを使う場合の設定
    environment:
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu

  # yamlを読み取るコンテナ
  yml-read:
    stdin_open: true
    tty: true
    volumes:
      - ./names.csv:/names.csv
      - ./docker-compose.yml:/docker-compose.yml
    container_name: yml-read
    build:
      context: ./yml-read
      dockerfile: Dockerfile

  # nvccコンテナ
  nvcc:
    container_name: "nvcc"
    build:
      context: ./nvcc
      dockerfile: Dockerfile
    volumes:
      - "../workspace:/workspace"
    tty: true

    #GPUを使う場合の設定
    environment:
      - "NVIDIA_VISIBLE_DEVICES=all"
      - "NVIDIA_DRIVER_CAPABILITIES=all"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
              - gpu